name: Custom Sing-box Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        shell: bash
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v-custom")
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Defined version: $VERSION"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.7'

      - name: Build Sing-box
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          mkdir -p output
          FILENAME="sing-box-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "windows" ]; then
            FILENAME="$FILENAME.exe"
          fi
          
          echo "Собираем $FILENAME ..."
          go build -v -trimpath -ldflags "-s -w -buildid= -checklinkname=0" -tags "with_quic,with_grpc,with_dhcp,with_utls,with_gvisor,with_naive_outbound,with_purego,badlinkname,tfogo_checklinkname0" -o output/$FILENAME ./cmd/sing-box

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*
          tag_name: "${{ env.APP_VERSION }}-custom-${{ github.run_number }}"
          name: "${{ env.APP_VERSION }} Build #${{ github.run_number }} (FallbackSite)"
          body: |
            Build with FallbackSite for NaiveProxy.
            Based on: **${{ env.APP_VERSION }}**